server:
  port: 1111
  
spring:
  application:
    name: api-gateway-service
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: http://localhost
      port: 8500
  profiles:
    active:
    - dev
  aop:
    proxy-target-class: true

zuul:
  routes:  
    authorization-server:
      path: /authorization-server/**
      sensitiveHeaders:
      serviceId: authorization-server
    account-service:
      path: /account-service/**
      sensitiveHeaders: 
      serviceId: account-service
    employee-service:
      path: /employee-service/**
      sensitiveHeaders: 
      serviceId: employee-service

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      client-id: commandlineinterface
      client-secret: commandlineinterface
    resource:
      user-info-uri: http://localhost:9999/user
      preferTokenInfo: false
  sessions: ALWAYS
  basic:
    enabled: false
  
logging:
  level:
    root: INFO 
    org.springframework.web: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/api-gateway-service/api-gateway-service.log